import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { dirname, join, posix, relative, sep } from 'node:path';

import { emitStylesheet } from '@noksha-ui/tailwind';
import { DEFAULT_BRAND, parseColor } from '@noksha-ui/tokens';

import {
  CONFIG_FILE,
  type Config,
  configPath,
  DEFAULT_REGISTRY,
  SCHEMA_URL,
  writeConfig,
} from '../config.js';
import { CliError } from '../errors.js';
import {
  detect,
  detectPackageManager,
  display,
  installCommand,
  missingDependencies,
} from '../project.js';
import { color, interactive, log, prompt, symbol } from '../ui.js';

export interface InitOptions {
  root: string;
  brand?: string | undefined;
  css?: string | undefined;
  dir?: string | undefined;
  alias?: string | undefined;
  registry?: string | undefined;
  yes: boolean;
  force: boolean;
}

const STYLESHEET = 'noksha.css';

/**
 * Sets a project up to own Noksha components: writes the theme, points Tailwind
 * at the directory the components will live in, and records the answers so
 * `add` and `diff` need no arguments.
 */
export async function init(options: InitOptions): Promise<void> {
  const { root, force, yes } = options;

  if (!force && (await exists(configPath(root)))) {
    throw new CliError(
      `${CONFIG_FILE} already exists in ${root}.`,
      'Pass --force to rewrite it. Your installed components are recorded there, so this discards what `diff` knows.',
    );
  }

  const detected = await detect(root);
  const ask = !yes && interactive();

  if (!ask && !yes && !interactive()) {
    log.info('Not a terminal — taking the detected defaults. Pass flags to override them.');
  }

  const brand = await resolveBrand(options.brand, ask);

  const cssEntry =
    options.css ??
    (ask
      ? await prompt(
          'Which stylesheet does Tailwind compile?',
          detected.css ?? 'src/app/globals.css',
        )
      : (detected.css ?? 'src/app/globals.css'));

  const components =
    options.dir ??
    (ask ? await prompt('Where should components go?', detected.components) : detected.components);

  const aliasDefault = options.dir === undefined ? detected.alias : null;
  const alias =
    options.alias ??
    (ask
      ? emptyToNull(
          await prompt(
            `Import alias for those files? ${color.dim('(blank for relative imports)')}`,
            aliasDefault ?? '',
          ),
        )
      : aliasDefault);

  const config: Config = {
    $schema: SCHEMA_URL,
    registry: options.registry ?? DEFAULT_REGISTRY,
    brand,
    css: normalise(cssEntry),
    components: normalise(components),
    alias,
    tsx: detected.tsx,
    installed: {},
  };

  log.plain();

  const stylesheet = await writeStylesheet(root, config);
  await ensureImport(root, config, stylesheet);
  await writeConfig(root, config);

  log.success(`Wrote ${color.bold(CONFIG_FILE)}`);
  log.plain();

  await reportNextSteps(root, detected.tsx);
}

/**
 * The seed the whole palette is generated from.
 *
 * Validated here rather than at first use: a typo'd hex should fail before any
 * file is written, not leave a project half-configured.
 */
async function resolveBrand(given: string | undefined, ask: boolean): Promise<string> {
  const raw =
    given ??
    (ask
      ? await prompt('Brand colour to generate the palette from?', DEFAULT_BRAND)
      : DEFAULT_BRAND);

  if (parseColor(raw) === null) {
    throw new CliError(
      `"${raw}" is not a colour this can parse.`,
      'Give a hex value, an rgb() or an oklch() — for example #6D4AFF.',
    );
  }
  return raw;
}

/**
 * Writes the theme next to the stylesheet Tailwind already compiles.
 *
 * The CSS is produced by the same `emitStylesheet()` the published package
 * builds `dist/styles.css` with, so a project that owns its components gets
 * byte-for-byte the tokens, tone rules and keyframes the package would have
 * given it — only with its own brand seeded in.
 */
async function writeStylesheet(root: string, config: Config): Promise<string> {
  const cssDir = dirname(join(root, config.css));
  const target = join(cssDir, STYLESHEET);

  /**
   * Tailwind v4 only generates utilities for classes it can find as literal
   * text. The components are about to be written somewhere it has no reason to
   * look, so the directory is registered here — relative to this stylesheet,
   * which is where Tailwind resolves `@source` from.
   */
  const source = toPosix(relative(cssDir, join(root, config.components)));

  const css = emitStylesheet({
    brand: config.brand,
    sources: [source.startsWith('.') ? source : `./${source}`],
    banner: `/*!
 * Noksha UI — generated by \`noksha init\`. Do not edit by hand.
 *
 * Regenerate with a different palette:
 *   npx @noksha-ui/cli init --force --brand '#0EA5E9'
 */`,
  });

  await mkdir(cssDir, { recursive: true });
  await writeFile(target, css, 'utf8');

  log.success(`Wrote ${color.bold(display(root, target))} ${color.dim(`(brand ${config.brand})`)}`);
  return target;
}

/**
 * Adds the `@import` to the project's stylesheet, after Tailwind's own.
 *
 * Order matters and is not cosmetic: `@import` rules must precede every other
 * rule in a CSS file, and the theme has to come after `tailwindcss` so its
 * `@theme` block resolves. Rather than guess at a file we did not write, this
 * only edits when it can find that anchor, and otherwise prints the line.
 */
async function ensureImport(root: string, config: Config, stylesheet: string): Promise<void> {
  const entry = join(root, config.css);
  const specifier = `./${toPosix(relative(dirname(entry), stylesheet))}`;
  const statement = `@import "${specifier}";`;

  let source: string;
  try {
    source = await readFile(entry, 'utf8');
  } catch {
    log.warn(
      `No ${display(root, entry)} to import from. Add this to the stylesheet Tailwind compiles:`,
    );
    log.plain(`  ${color.cyan(statement)}`);
    return;
  }

  if (source.includes(specifier)) {
    log.step(`${display(root, entry)} already imports it`);
    return;
  }

  const anchor = /^[ \t]*@import\s+['"]tailwindcss[^'"]*['"][^;]*;[ \t]*$/m.exec(source);

  if (anchor?.index === undefined) {
    log.warn(`Could not find the Tailwind import in ${display(root, entry)}. Add this after it:`);
    log.plain(`  ${color.cyan(statement)}`);
    return;
  }

  const at = anchor.index + anchor[0].length;
  await writeFile(entry, `${source.slice(0, at)}\n${statement}${source.slice(at)}`, 'utf8');

  log.success(`Imported it from ${color.bold(display(root, entry))}`);
}

async function reportNextSteps(root: string, tsx: boolean): Promise<void> {
  if (!tsx) {
    log.warn(
      'No tsconfig.json here — the components are TypeScript and will need a project that compiles it.',
    );
    log.plain();
  }

  const missing = await missingDependencies(root, ['@noksha-ui/core']);

  if (missing.length > 0) {
    const manager = await detectPackageManager(root);
    log.plain(color.bold('Next:'));
    log.plain(`  ${color.dim(symbol.arrow)} ${color.cyan(installCommand(manager, missing))}`);
    log.plain(
      `    ${color.dim('the focus, dismiss and variant primitives the components import')}`,
    );
    log.plain(`  ${color.dim(symbol.arrow)} ${color.cyan('npx @noksha-ui/cli add button')}`);
  } else {
    log.plain(`${color.bold('Next:')} ${color.cyan('npx @noksha-ui/cli add button')}`);
  }
}

const exists = async (path: string): Promise<boolean> => {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
};

const toPosix = (path: string): string => path.split(sep).join(posix.sep);

const normalise = (path: string): string => toPosix(path).replace(/^\.\//, '').replace(/\/$/, '');

const emptyToNull = (value: string): string | null => (value.trim() === '' ? null : value.trim());
