import { reducedMotionTokens, scaleTokens, type TokenMap } from './scales.js';
import {
  type BuildThemeOptions,
  buildTheme,
  darkShadowTokens,
  shadowTokens,
  type Theme,
} from './semantic.js';

export const PREFIX = 'prism';

/** `bg-canvas` → `--prism-bg-canvas`. */
export function varName(token: string): string {
  return `--${PREFIX}-${token}`;
}

/** `bg-canvas` → `var(--prism-bg-canvas)`. */
export function cssVar(token: string, fallback?: string): string {
  return fallback ? `var(${varName(token)}, ${fallback})` : `var(${varName(token)})`;
}

function declarations(tokens: TokenMap, indent: string): string {
  return Object.entries(tokens)
    .map(([name, value]) => `${indent}${varName(name)}: ${value};`)
    .join('\n');
}

function block(selector: string, tokens: TokenMap, indent = ''): string {
  return `${indent}${selector} {\n${declarations(tokens, `${indent}  `)}\n${indent}}`;
}

export interface EmitCssOptions extends BuildThemeOptions {
  /** Emit the Layer 1 ramps too. Off by default — components never read them. */
  includePrimitives?: boolean;
  /** Emit the `prefers-reduced-motion` override. */
  includeReducedMotion?: boolean;
  /** Prebuilt theme, to avoid recomputing when you already have one. */
  theme?: Theme;
}

/**
 * Emits the complete stylesheet for a theme.
 *
 * Contrast is checked strictly here unless the caller opts out: this is the
 * build step, so a seed that cannot carry readable text should stop the build
 * rather than ship.
 *
 * Dark mode is written through three selectors so every setup works unchanged:
 * a `.dark` class (Tailwind's convention), a `[data-theme]` attribute (next-themes),
 * and a `prefers-color-scheme` query for consumers who never wire up a toggle.
 * The media query is guarded against an explicit light choice so an opt-out
 * always beats the OS preference.
 */
export function emitThemeCss(options: EmitCssOptions): string {
  const {
    includePrimitives = false,
    includeReducedMotion = true,
    strictContrast = true,
    theme: prebuilt,
    ...seeds
  } = options;
  const theme = prebuilt ?? buildTheme({ ...seeds, strictContrast });

  const rootTokens: TokenMap = {
    ...(includePrimitives ? theme.primitives : {}),
    ...theme.light,
    ...shadowTokens,
    ...scaleTokens,
  };

  const parts = [
    '/* Generated by @prism-ui/tokens — do not edit by hand. */',
    block(':root', rootTokens),
    '',
    '/* Explicit dark: class or data attribute. */',
    block(":root.dark,\n[data-theme='dark']", { ...theme.dark, ...darkShadowTokens }),
    '',
    '/* System dark, unless the consumer has explicitly opted into light. */',
    '@media (prefers-color-scheme: dark) {',
    block(
      ":root:not(.light):not([data-theme='light'])",
      { ...theme.dark, ...darkShadowTokens },
      '  ',
    ),
    '}',
  ];

  if (includeReducedMotion) {
    parts.push(
      '',
      '/* One block zeroes motion library-wide, because every animation reads these. */',
      '@media (prefers-reduced-motion: reduce) {',
      block(':root', reducedMotionTokens, '  '),
      '}',
    );
  }

  return `${parts.join('\n')}\n`;
}

/**
 * Emits only the semantic overrides for an extra theme, scoped to a selector.
 * This is the ~40-line block referenced in ARCHITECTURE.md §3 — a second brand
 * costs one of these, not a fork.
 */
export function emitThemeOverride(selector: string, options: BuildThemeOptions): string {
  const theme = buildTheme(options);
  return [
    block(selector, theme.light),
    '',
    block(`${selector}.dark, ${selector}[data-theme='dark']`, theme.dark),
    '',
  ].join('\n');
}
